### PR TITLE
Improve memory management and error handling

### PR DESCRIPTION
**Pull request by jafarre-viewnext**
- Using temporary files, input/output streams or scratch files instead of fully loading files into memory.
- Improved error handling.
- Temporary files are now guarranted to be removed when not needed anymore.
- Created generic utility class and extension to simplify temporary-file management.
- Fixed bugs in the /health endpoint.
- Small miscellaneous improvements and many warnings removed.

### CODE REVIEW

**Review by metmajer — APPROVED** [review]
🥇

**Comment by jafarre-viewnext** [comment]
I have detected a problem with the packaging of the app.jar, so this cannot be merged yet. Apparently, the problem was always there, but it doesn't always manifest.

**Comment by jafarre-viewnext** [comment]
The fix required activating the mergeGroovyExtensionModules transformation of the shadowJar plugin and also fixing a bug in the plugin code.
@metmajer please, review this latest change. Thank you.

**Review by metmajer — APPROVED** [review]
Thank you!

**Pull request merged**
